#+TITLE: DevOps Days Des Moines

* Links
- [[https://www.papercall.io/cfps/2796/submissions/new][Talk Submission]]

* Template
- Title :: <Title>

- Elevator Pitch ::
  You have 300 characters to sell your talk. This is known as the "elevator pitch".
  Make it as exciting and enticing as possible.
 
- Talk Format ::
  What format is this talk best suited for?
  - 45 Minutes
  - 5 Minutes

- Audience Level ::
  Who is the best target audience for this talk?
  - All
  - Beginner
  - Intermediate
  - Advanced

- Description ::
  This field supports Markdown. The description will be seen by reviewers during the
  CFP process and may eventually be seen by the attendees of the event. You should
  make the description of your talk as compelling and exciting as possible. Remember,
  you're selling both the organizers of the events to select your talk, as well as
  trying to convince attendees your talk is the one they should see.

- Notes ::
  This field supports Markdown. Notes will only be seen by reviewers during the CFP
  process. This is where you should explain things such as technical requirements, why
  you're the best person to speak on this subject, etc...

- Tags ::
  Tag your talk to make it easier for event organizers to be able to find.
  Examples are "ruby, javascript, rails".


